### ISSUE TITLE
出现了个报错，大神帮帮忙？

### ISSUE THREAD

**Issue by MrRegret** [cyanzhong/Retriever#6]
Failed to create provisioning profile. The app ID "app.cyan.retriever" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.
No profiles for 'app.cyan.retriever' were found:  Xcode couldn't find a provisioning profile matching 'app.cyan.retriever'.
Code signing is required for product type 'Application' in SDK 'iOS 10.1'

**Comment by cyanzhong** [comment]
换个 bundle id
