### ISSUE TITLE
xcode7 exception

### ISSUE THREAD

**Issue by FWBGitHub** [cyanzhong/Retriever#7]
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<LSApplicationProxy 0x7fad6ae37390> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _infoDictionary.'

**Comment by cyanzhong** [comment]
compability: greater than or equal to iOS 10.0

**Comment by FWBGitHub** [comment]
OK，Thanks
